from .pipeline import PassPipeline
from .validate import ValidatePass
from .dead_code import DeadCodePass
from .constant_fold import ConstantFoldPass
from .verify import VerifyPass
from .mem2reg import Mem2RegPass
from .copyprop import CopyPropagationPass
from .verify_ssa import VerifySSA
from .gvn import GVN
from .inline import Inline
